<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUtje8kn\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUtje8kn/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerUtje8kn.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerUtje8kn\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerUtje8kn\appProdProjectContainer([
    'container.build_hash' => 'Utje8kn',
    'container.build_id' => 'b77a40af',
    'container.build_time' => 1566245939,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUtje8kn');
